---

- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"

- name: Install java
  include_tasks: java.yml
  when: es_java_install

- name: Include optional user and group creation.
  include_tasks: logstash-optional-users.yml
  when: (logstash_group is defined) and (logstash_user is defined)

- name: Install tasks for Debian systems
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Copy new config files - templated
  template: src={{ item }} dest={{logstash_conf_dir}}/{{ item | basename | regex_replace('\.j2','') }}
  with_fileglob:
    - ../templates/conf/*.j2

- name: Copy new config files - non-templated
  copy: src={{ item }} dest={{logstash_conf_dir}}/{{ item | basename }}
  with_fileglob:
    - ../files/*.conf

- name: Install plugins
  include_tasks: plugins.yml

# This will always run...

- name: Enabling logstash service upon boot & restarting
  debug: msg="Finished installing logstash. Reloading systemd config & Restarting"
  notify:
    - reload systemd configuration
    - restart logstash
  changed_when: True

