---

- name: Get list of installed plugins.
  command: "{{logstash_home_dir}}/bin/logstash-plugin list"
  register: logstash_plugins_list

- name: Install configured plugins.
  command: "{{logstash_home_dir}}/bin/logstash-plugin install {{ item }}"
  with_items: "{{ logstash_install_plugins }}"
  when: "item not in logstash_plugins_list.stdout"
