---

- name: Ensure dependency is installed (Ubuntu).
  apt:
    name: apt-transport-https
    state: present

- name: Add Elasticsearch apt key.
  apt_key:
    url: "{{ es_apt_key }}"
    state: present

- name: Add logstash repository.
  apt_repository:
    repo: "{{ es_apt_url }}"
    state: present
    update_cache: yes

- name: Install Logstash
  apt:
#    name: logstash{% if logstash_version is defined and logstash_version != "" %}={{ logstash_version }}{% endif %}
    name: logstash
    state: present
    allow_unauthenticated: "{{ 'no' if es_apt_key else 'yes' }}"
    cache_valid_time: 86400

- name: Create Directories
  file: path={{ item }} state=directory recurse=yes
  with_items:
    - "{{logstash_home_dir}}"
    - "{{logstash_settings_dir}}"
    - "{{logstash_conf_dir}}"
    - "{{logstash_logs_dir}}"
    - "{{logstash_data_dir}}"
    - "{{logstash_pid_dir}}"

- name: Change ownership
  file: path={{ item }} state=directory recurse=yes owner={{ logstash_user }} group={{ logstash_group }}
  with_items:
    - "{{logstash_home_dir}}"
    - "{{logstash_settings_dir}}"
    - "{{logstash_conf_dir}}"
    - "{{logstash_logs_dir}}"
    - "{{logstash_data_dir}}"
    - "{{logstash_pid_dir}}"
  when: (logstash_group is defined) and (logstash_user is defined)

# remove some default files

- name: Delete other default config files
  file: path={{ item }} state=absent
  with_items:
    - "/etc/systemd/system/logstash.service"
    - "/etc/default/logstash"

- name: Copy new configuration files for this instance
  template: src={{ item }} dest={{logstash_settings_dir}}/{{ item | basename | regex_replace('\.j2','') }} mode=0644
  with_fileglob:
    - ../templates/*.j2

#Copy the systemd specific files

- name: Copy environment file that can be used by logstash.service
  template: src=systemd/logstash.environment.j2 dest={{logstash_environment}} mode=0644 force=yes

- name: Copy systemd file for this instance
  template: src=systemd/logstash.service.j2 dest={{logstash_service}} mode=0644 force=yes

